export type TypographyTitleType = {
  fontSize?: string;
  color?: string;
  xl?: boolean;
  xl2?: boolean;
  xl3?: boolean;
  xl4?: boolean;
  xl5?: boolean;
  xl6?: boolean;
  xl7?: boolean;
  xl8?: boolean;
  xl9?: boolean;
  thin?: boolean;
  extralight?: boolean;
  light?: boolean;
  normal?: boolean;
  medium?: boolean;
  semibold?: boolean;
  bold?: boolean;
  extrabold?: boolean;
  black?: boolean;
  noMarginBottom?: boolean;
};
